version: '3.8'
services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3456:3456
      - 3457:3457
    volumes:
      - $(PWD)/volumes/logs:/app/logs
    environment:
      - APP_ENV=production
